#Global api config for Repliers
# https://api.repliers.io/listings?resultsPerPage=100&type=lease&type=sale&fields=soldDate,address.city,address.area,address.district,address.neighborhood,address.zip,details.numBathrooms,details.numBedrooms,details.style,listPrice,listDate,details.sqft,details.propertyType,details.numParkingSpace,details.numGarageSpaces,details.numKitchens,details.numDrivewaySpaces,details.description,details.numParkingSpaces,details.extras,details.numRooms,condominium.ammenities,condominium.fees,nearby.ammenities,type,class,map,soldPrice&pageNum={i}&minSoldDate={start_date}&maxSoldDate={end_date}&class=condo&class=residential&status=U&lastStatus=Lsd&lastStatus=Sld"
listings_parameters = {
    "resultsPerPage": 100,
    "type": ["lease","sale"],
    "fields" : "soldDate,address.city,address.area,address.district,address.neighborhood"
                ",address.zip,details.numBathrooms,details.numBedrooms,details.style,listPrice,"
                "listDate,details.sqft,details.propertyType,details.numParkingSpace,details.numGarageSpaces,"
                "details.numKitchens,details.numDrivewaySpaces,details.description,details.numParkingSpaces,"
                "details.extras,details.numRooms,condominium.ammenities,condominium.fees,nearby.ammenities,"
                "type,class,map,soldPrice",
    "class" : ["condo","residential"],
    "status": "U",
    "lastStatus": ["Lsd","Sld"]
}
"https://api.repliers.io/listings?type={type}&listings=false&neighborhood={location}&status=U&lastStatus={lastStatus}&statistics=grp-mth,avg-listPrice,avg-soldPrice,cnt-available,cnt-closed,med-daysOnMarket,avg-daysOnMarket,med-soldPrice,med-listPrice&minBeds={bed}&maxBeds={bed}&minSoldDate=2021-01-01&maxSoldDate=2023-12-31&minListDate=2021-01-01&maxListDate=2023-12-31"
neighbourhoods_parameters = {
    "listings": "false",
    "status": "U",
    "statistics": "grp-mth,avg-listPrice,"
                  "avg-soldPrice,cnt-available,cnt-closed,"
                  "med-daysOnMarket,avg-daysOnMarket,med-soldPrice,med-listPrice"
}



neighbourhoods = [
    'Waterfront Communities C1',
    'Church-Yonge Corridor',
    'Bay Street Corridor',
    'City Centre',
    'Willowdale East',
    'Niagara',
    'Mimico',
    'Waterfront Communities C8',
    'Mount Pleasant West',
    'Unionville',
    'Islington-City Centre West',
    'Bayview Village',
    'Annex',
    'Moss Park',
    'Hurontario',
    'Henry Farm',
    'Rural Oakville',
    'Vaughan Corporate Centre',
    'Bowmanville',
    'Northwest Brampton',
    'South Riverdale',
    'Willowdale West',
    'Langstaff',
    'Stoney Creek',
    'Sandringham-Wellington',
    'Central Erin Mills',
    'Concord',
    'Churchill Meadows',
    'Patterson',
    'Central',
    'Bendale',
    'Lakeview',
    'Stouffville',
    'Woburn',
    'Banbury-Don Mills',
    'Agincourt South-Malvern West',
    'Dovercourt-Wallace Emerson-Junction',
    'High Park-Swansea',
    'Erin Mills',
    'Maple',
    "Fletcher's Meadow",
    'Bradford',
    'Georgetown',
    'Downsview-Roding-CFB',
    'Vellore Village',
    'Kensington-Chinatown',
    'Waterdown',
    'East Credit',
    'West Oak Trails',
    'Regent Park',
    'Bram East',
    'Little Portugal',
    'The Beaches',
    'Windfields',
    'Don Valley Village',
    'Orangeville',
    'Alcona',
    'Cornell',
    'Courtice',
    'Cooksville',
    'Meadowvale',
    'Lindsay',
    'Clanton Park',
    'Mount Pleasant East',
    'Malvern',
    'Credit Valley',
    'Wasaga Beach',
    'Rural Caledon',
    'Wismer',
    'Clarkson',
    'Brant',
    'Rosedale-Moore Park',
    'Lansing-Westgate',
    'Newtonbrook West',
    'Orillia',
    "L'Amoreaux",
    'Ancaster',
    'Newtonbrook East',
    'Bronte West',
    'Alliston',
    'Cobourg',
    'Painswick South',
    'Stonegate-Queensway',
    "Tam O'Shanter-Sullivan",
    'Haldimand',
    'Lisgar',
    'Old Oakville',
    'South East',
    'Yonge-Eglinton',
    'Holly',
    'Bram West',
    'Yorkdale-Glen Park',
    'Birchcliffe-Cliffside',
    'Uptown Core',
    'Commerce Valley',
    'Berczy',
    'Collingwood',
    'Monaghan',
    'Yonge-St. Clair',
    'Glen Abbey',
    'Samac',
    'Trinity-Bellwoods',
    'Northcrest',
    'Pringle Creek',
    'Ardagh',
    'Alton',
    'University',
    'Cabbagetown-South St. James Town',
    'Junction Area',
    'Oak Ridges',
    'River Oaks',
    'Keswick South',
    'Appleby',
    'Dorset Park',
    'Rural Innisfil',
    'Wexford-Maryvale',
    'Innis-Shore',
    'SE',
    'Beverley Glen',
    'Crosby',
    'Roncesvalles',
    'Bay Ridges',
    'West Hill',
    'Flemingdon Park',
    'Parkwoods-Donalda',
    'Ford',
    'Bedford Park-Nortown',
    'Jefferson',
    'West Humber-Clairville',
    'Rouge E11',
    'LaSalle',
    'Meadowvale Village',
    'York University Heights',
    'Donevan',
    'North Richvale',
    'Central West',
    'East Woodbridge',
    "O'Neill",
    'Port Credit',
    'Newcastle',
    'Crestwood-Springfarm-Yorkhill',
    'Madoc',
    'Brooklin',
    'Rural Whitby',
    'North St. James Town',
    'High Park North',
    'Beaty',
    'Clairlea-Birchmount',
    'Dempsey',
    'Greensborough',
    'Williamsburg',
    'Holland Landing',
    'East End-Danforth',
    'Leaside',
    'Long Branch',
    'Iroquois Ridge North',
    'Applewood',
    'Northeast Ajax',
    'Eastdale',
    'Clarke',
    'Doncrest',
    'Angus',
    'Erindale',
    'Palmerston-Little Italy',
    'Oakwood Village',
    'Greenwood-Coxwell',
    'Willmott',
    'West Woodbridge',
    'Oak Ridges Lake Wilcox',
    'Mississauga Valleys',
    'Kleinburg',
    'Taunton',
    'Bronte East',
    'Agincourt North',
    'Danforth Village-East York',
    'Queen Street Corridor',
    'South Parkdale',
    'Thornhill',
    'Brampton North',
    'Rural Smith-Ennismore-Lakefield',
    'Palermo West',
    'McLaughlin',
    'Lawrence Park South',
    'Forest Hill South',
    'Northwest Ajax',
    'Rathwood',
    'St. Andrew-Windfields',
    'Bristol-London',
    'Rural Pickering',
    'Steeles',
    'Orchard',
    'Rolling Acres',
    'Lawrence Park North',
    'Casa Loma',
    'Malton',
    'Central Park',
    'Aurora Highlands',
    'Paris',
    'Woodland Hill',
    'Grange Hill East',
    'Westbrook',
    'Otonabee',
    'Englemount-Lawrence',
    'Rouge Woods',
    'Central Newmarket',
    'South Richvale',
    'Hillcrest Village',
    'Keswick North',
    'Milliken',
    'Centennial',
    'Edenbridge-Humber Valley',
    'Stoney Creek Mountain',
    'SW',
    'Stonehaven-Wyndham',
    "Fletcher's Creek South",
    'Rockcliffe-Smythe',
    'Harrison',
    'Port Hope',
    'Weston-Pellam Park',
    'Blue Grass Meadows',
    'Milliken Mills East',
    'Sharon',
    'Northgate',
    'Downtown Brampton',
    'Bathurst Manor',
    'Summerhill Estates',
    'Humewood-Cedarvale',
    'Ashburnham',
    'Crown Point',
    'Westminster-Branson',
    'Cliffcrest',
    'Downtown',
    'Middlefield',
    'Etobicoke West Mall',
    'Rural Vaughan',
    'Harding',
    'Vanier',
    'Eglinton East',
    'Eringate-Centennial-West Deane',
    'Streetsville',
    'Pleasant View',
    'Brampton West',
    'Brownridge',
    'Lynde Creek',
    'Pinecrest',
    'Rural Aurora',
    'College Park',
    'Downtown Whitby',
    'Observatory',
    "O'Connor-Parkview",
    'Briar Hill-Belgravia',
    'Shelburne',
    'Brampton East',
    'East York',
    'Liverpool',
    'North I',
    'Mill Pond',
    'Rural Galway-Cavendish and Harvey',
    'Uxbridge',
    'Midland',
    'Rural Richmond Hill',
    'Duffin Heights',
    'East I',
    'Alderwood',
    'Fergus',
    'Heart Lake West',
    'Roseland',
    'Dundas',
    'Binbrook',
    'Mineola',
    'Scott',
    'Mount Olive-Silverstone-Jamestown',
    'Weston',
    'Gorham-College Manor',
    'South X',
    'Aileen-Willowbrook',
    'Eastlake',
    'Cedarwood',
    'Brookhaven-Amesbury',
    'Brighton',
    'Kingsview Village-The Westway',
    'North S',
    'Headon',
    'Aurora Village',
    'Willowridge-Martingrove-Richview',
    'Port Perry',
    'Port Whitby',
    'Aurora Heights',
    "Sutton & Jackson's Point",
    'Central East',
    'New Toronto',
    'Southgate',
    'Woodbine Corridor',
    'Wychwood',
    'Corso Italia-Davenport',
    'Tottenham',
    'Bayview Wellington',
    "Fletcher's West",
    'Rose',
    'Dufferin Grove',
    'South West',
    'South V',
    'Scarborough Village',
    'Bridle Path-Sunnybrook-York Mills',
    'Runnymede-Bloor West Village',
    'Shoreacres',
    'Morningside',
    'Huron Heights-Leslie Valley',
    'Kennedy Park',
    'Bayview Northeast',
    'Rural Tiny',
    'Pine Ridge',
    'Glenfield-Jane Heights',
    'Sheridan',
    'North Riverdale',
    'Keelesdale-Eglinton West',
    'Victoria Village',
    'Beasley',
    'Lorne Park',
    'Town Centre',
    'Sonoma Heights',
    'Brant Hills',
    'Creditview',
    'Cobban',
    'Thorncliffe Park',
    'Amberlea',
    'East G',
    'North R',
    'Royal Orchard',
    'North C',
    'Coates',
    'North M',
    'NW',
    'Brampton South',
    'NE',
    'Devonsleigh',
    'Woodbine-Lumsden',
    'Northwood Park',
    'Northwest Sandalwood Parkway',
    'Markham Village',
    'Westgate',
    'Norfolk',
    'Markland Wood',
    'South B',
    'Mount Hope',
    'Guildwood',
    'Queensville',
    'Tansley',
    'Acton',
    'Taunton North',
    'Fenelon Falls',
    'Beaverton',
    'Box Grove',
    'Centennial Scarborough',
    'East H',
    'Painswick North',
    'East C',
    'Fairview',
    'Danforth',
    'East F',
    'Dundalk',
    'Campbellford',
    'Gibson',
    'Bolton East',
    'West Shore',
    'Angus Glen',
    'Snelgrove',
    'Kingsway South',
    'North B',
    'Bobcaygeon',
    'Mountainside',
    'Grandview',
    'Heart Lake East',
    'Avondale',
    'Bayview Woods-Steeles',
    'East D',
    'Village Green-South Unionville',
    'South U',
    'Ottawa',
    'Vaughan Grove',
    'Rural Otonabee-South Monaghan',
    'Rouge E10',
    'Rural Clarington',
    'North F',
    'Letitia Heights',
    'King City',
    'Iroquois Ridge South',
    'Rural Whitchurch-Stouffville',
    'Rural Trent Hills',
    'Caledonia-Fairbank',
    'Old Milton',
    'Highland Creek',
    'Ainslie Wood',
    'Kortright Hills',
    'West Willow Woods',
    'Rural Douro-Dummer',
    'South F',
    'Grove East',
    'Vales of Castlemore',
    'South W',
    'Glenway Estates',
    'Blue Mountain Resort Area',
    'Rural Cavan Monaghan',
    'Mt Albert',
    'South K',
    'Humber Heights',
    'Rural Oro-Medonte',
    'Lakeshore',
    'Princess-Rosethorn',
    'South Y',
    'Islington Woods',
    'East A',
    'Victoria Square',
    "Fletcher's Creek Village",
    'Crescent Town',
    'Vincent',
    'Rural Mono',
    'Rural Scugog',
    'Sandringham-Wellington North',
    'North G',
    'Black Creek',
    'Sunnidale',
    'Rural Barrie Southeast',
    'Guelph South',
    'Rural North Kawartha',
    'Bolton West',
    'Markville',
    'Brock Ridge',
    'Georgian Drive',
    'Rural Uxbridge',
    'Humbermede',
    'Kirkendall',
    'Bayview Hill',
    'Cathedraltown',
    'Village East',
    'South T',
    'Uptown',
    'Broadview North',
    'Walker',
    'Durand',
    'Elora/Salem',
    'East B',
    'Nobleton',
    'Palmer',
    'Timberlea',
    'East K',
    'Humber Summit',
    'Raymerville',
    'Humberlea-Pelmo Park W5',
    'Penetanguishene',
    'Dunnville',
    'Simcoe',
    'South O',
    'North P',
    'Rural Havelock-Belmont-Methuen',
    'Caledon East',
    'Milliken Mills West',
    'Lefroy',
    'Blake-Jones',
    'Mount Dennis',
    'South E',
    'North N',
    'Brechin',
    'Ionview',
    'Rustic',
    'Clearview',
    'Forest Hill North',
    'East M',
    'AY',
    'Elms-Old Rexdale',
    'Two Rivers',
    'Allandale',
    'Wellington',
    'Brantford Twp',
    'Hannon',
    'Homeside',
    'Oakridge',
    'Bullock',
    'Waverley',
    'Cachet',
    'Cundles East',
    'Playter Estates-Danforth',
    'Maple Leaf',
    'Rural Ramara',
    'Rural Severn',
    'North E',
    'Little Lake',
    'Rockwood',
    'Landsdale',
    'Freeman',
    'Goreway Drive Corridor',
    'Rexdale-Kipling',
    'Millbrook',
    'Rural Hamilton',
    'Historic Lakeshore Communities',
    'Colborne',
    'Clairfields',
    'Bolton North',
    'Sarnia',
    'South D'
]