name: tests
on: [push]
jobs:
  check_code_quality_and_installation:
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v3
        - name: List files in the repository
          run: |
            ls ${{ github.workspace }}
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: Run Make Commands
          run: | 
            make install
            make quality
  run_tests:
    runs-on: ubuntu-latest
    steps:
        - name: Check out code
          uses: actions/checkout@v2
          with:
            submodules: true
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
        - name: Run tests
          env:
            REPLIERS_KEY: ${{ secrets.REPLIERS_KEY }}
          run: |
            make install
            make predictor_tests